package aka_ecliptic.com.cinephile.Model;

public enum Genre{
    ACTION, ADVENTURE, COMEDY, CRIME, DOCUMENTARY, DRAMA, FAMILY, FANTASY, HISTORY, HORROR, MUSIC,
    MYSTERY, ROMANTIC, SCI_FI, THRILLER, WAR, WESTERN, NONE
}
